.MODEL SMALL
.STACK 100H
.DATA
.CODE
MAIN PROC
    
    
MOV BL,1          ;BL HOLDS STARTING POINT (STARTING POINT 1)
MOV CX, 5         ;CX HOLDS INPUT COUNTER (5 INPUTS)
MOV AL,0          ;AL HOLDS WHAT IS INITIALLY HAVE TO SUM (ADD 0 INITIALLY)

L1: ADD AL,BL     ;ADDING 0+1=1 AND STORE IN AL
ADD BL,2          ;INCREMENT BL VALUE BY 2

LOOP L1           ;LOOP IT
NOP               ;NO OPERATION
.EXIT



MAIN ENDP
END MAIN    