.MODEL SMALL
.STACK 100H
.DATA
.CODE
MAIN PROC

MOV AX,@DATA
MOV DS,AX    
    
MOV BL,2          ;BL HOLDS STARTING POINT (STARTING POINT 2)
MOV CX,3          ;CX HOLDS INPUT COUNTER (3 INPUTS)
MOV AL,1          ;AL HOLDS WHAT IS INITIALLY HAVE TO MULTIPLY (MULTIPLY WITH 1 INITIALLY)

L1: MUL BL        ;MULTIPLYING 1*2=2 AND STORE IN AL
ADD BL,2          ;INCREMENT BL VALUE BY 2

LOOP L1           ;LOOP IT
NOP               ;NO OPERATION
.EXIT



MAIN ENDP
END MAIN    