.MODEL SMALL
.STACK 100H
.DATA
.CODE

     MAIN PROC
    
      
MOV BX,6         ;BX HOLDS STARTING POINT (STARTING POINT 6) 
MOV CX,6         ;CX HOLDS INPUT COUNTER (6 INPUTS=6,5,4,3,2,1)
MOV AX,1         ;AX HOLDS WHAT IS INITIALLY HAVE TO MULTIPLY (MULTIPLY 1 INITIALLY)

START:
MUL BX           ;MULTIPLYING 6*1=6 AND STORE IN AX
DEC BX           ;DECREMENT BX VALUE BY 1
LOOP START       ;LOOP IT


      MAIN ENDP


END MAIN