.MODEL SMALL
.STACK 100H
.DATA
.CODE

MAIN PROC
    
    MOV AL,90H
    MOV BL,82H    ;IN ASCII 82=e COMES FIRST
    CMP AL,BL      
    JB PRINTAL    ;JUMP IF AL IS BELOW BL (AL<BL)
    
    MOV AH,2
    MOV DL,BL     ;PRINT BL
    INT 21H
    
    JMP RETURN
    
    PRINTAL:
    MOV AH,2
    MOV DL,AL     ;PRINT AL (IT WILL NOT PRINT SINCE IT COMES SECOND)
    INT 21H
    
    RETURN:
    MOV AH,4CH
    INT 21H
    
MAIN ENDP

END MAIN