.MODEL SMALL
.STACK 100H
.DATA
.CODE

MAIN PROC
    
    MOV AL,90H
    MOV BL,82H    ;IN ASCII 82=e COMES FIRST
    MOV AH,2
    CMP AL,BL      
   JG ELSE_    ;AL VALUE IS GREATER THAN BL VALUE? YES BECAUSE TINY BL COMES FIRST
   
   MOV DL,AL   ;AL COMES SENCOND SO DONT PRINT IT
   JMP DISPLAY
   
   
   ELSE_:
   MOV DL,BL  ;BL COMES FIRST(SMALL VALUE) PRINT IT
   DISPLAY:
   INT 21H
   
 END_IF:  
    
MAIN ENDP

END MAIN